### ISSUE TITLE
Not working in iOS 13.3.2

### ISSUE THREAD

**Issue by oveappnap** [benoit-pereira-da-silva/SoundWaveForm#2]
Not working on iOS 13.3.2 or higher but works on 13.3.1.

**Comment by benoit-pereira-da-silva** [comment]
Dear @oveappnap,

I've been publishing the version 4.0.1. Could you test test it and give me a more detailed feed back in case of failure?

**Comment by benoit-pereira-da-silva** [comment]
I've been publishing the version 4.0.2. Could you test test it and give me a more detailed feed back in case of failure?
