### ISSUE TITLE
Not support SPM ?

### ISSUE THREAD

**Issue by k-motoyan** [benoit-pereira-da-silva/SoundWaveForm#4]
I'm thinking of using this library, but I don't recommend using Carthage in my current project.
Is there any reason why it doesn't support SPM right now?

**Comment by benoit-pereira-da-silva** [comment]
I ve been updating the project to support Xcode 12, while  keeping retro compatibility support. Carthage is not a must I will try to provide SPM guideline.

**Comment by benoit-pereira-da-silva** [comment]
SPM should be normally supported now. Could you confirm it works for you?

**Comment by k-motoyan** [comment]
Thank you!
I was able to successfully add this library to my project with SPM!!
