### ISSUE TITLE
Support x86_64 architectures

### ISSUE THREAD

**Issue by qsd-faris** [benoit-pereira-da-silva/SoundWaveForm#5]
When the library is installed by SPM and when trying to build on iOS simulator, this error is shown:
`Could not find module 'SoundWaveForm' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator'...`
and Xcode is forcing us to use `Rosetta` to be able to build.

**Comment by benoit-pereira-da-silva** [comment]
Dear qsd-faris could you explain how you fixed your issue?

**Comment by qsd-faris** [comment]
hi @benoit-pereira-da-silva ,
Maybe it is not the issue in the library, I changed the scheme and it worked fine. For some reason, one of my 3 schemes is having this issue(most likely because of some Build Settings) and I am trying to find out why.
Did you try to run using SPM on iOS simulator? Does it work fine for you?
